name: Install repository

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v0.3.0

    - name: Restore forge compilation cache
      uses: actions/cache/restore@v4
      with:
        path: |
          cache
          out
        key: forge-${{ github.ref_name }}
        restore-keys: |
          forge-${{ github.base_ref }}
          forge-
